name: uav_rsma
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - setuptools
  - wheel
  - pip:
      - absl-py==2.1.0
      - bcrypt==4.2.0
      - cffi==1.17.1
      - cmake==3.30.0
      - contourpy==1.2.1
      - cryptography==43.0.1
      - cycler==0.12.1
      - filelock==3.15.4
      - fonttools==4.53.1
      - grpcio==1.64.1
      - jinja2==3.1.4
      - kiwisolver==1.4.5
      - markdown==3.6
      - markupsafe==2.1.5
      - matplotlib==3.9.1
      - mpmath==1.3.0
      - networkx==3.3
      - numpy==1.26.4
      - packaging==24.1
      - paramiko==3.4.1
      - pillow==10.4.0
      - protobuf==4.25.3
      - pycparser==2.22
      - pynacl==1.5.0
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - scipy==1.14.0
      - scp==0.15.0
      - six==1.16.0
      - sympy==1.13.0
      - tensorboard==2.17.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - typing-extensions==4.12.2
      - werkzeug==3.0.3
